# Generated by Django 4.1.1 on 2022-09-10 20:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AppFami', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='vinculo',
            field=models.CharField(default=django.utils.timezone.now, max_length=60),
            preserve_default=False,
        ),
    ]
